# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Lean Kanban Central Europe"

email: "lkce@it-agile.de"
description: "World's biggest conference on Lean Kanban!"
baseurl: ""
url: "http://www.leankanbance.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "it-agile GmbH"
organizerAlternateName: "it-agile"
organizerDescription: "Consultancy for Agile methods"
organizerEmail: "lkce@it-agile.de"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.it-agile.de"

# Head
metaKeywords: "kanban, lean, event, leadership, change, agile, modern management, it-agile, LKU, germany, hamburg"
twitterAccount: "@LeanKanbanCE"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/cfp_lkce19"
#c4sponsorsUrl: "/assets/Sponsoring_LKCE18.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/socialevent/", text: "Social Event"}
 - {permalink: "/cod/", text: "Code of Conduct"}
 - {permalink: "/archive/", text: "Previous Events"}
bottomNavigationLinks:
  - {permalink: "/#tickets", text: "Buy tickets"}
  - {permalink: "/#subscribe", text: "Subscribe for updates"}

rightNavigationButtons:
  - {permalink: "/#tickets", text: "Buy tickets"}

# Hero Block
heroImage: "background.jpg"
heroTitle: "Lean Kanban Central Europe <typeout>"
eventDate: "5th + 6th November, 2019"
typeoutTextValues: '"", "2019"'
typeoutFallback: "2019"
heroButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}
 # - {link: "http://bit.ly/cfp_lkce19", text: "Become a speaker"}
 - {permalink: "/#subscribe", text: "Subscribe for updates"}

# About Block
aboutTitle: "About Lean Kanban Central Europe"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "Come and join us at the world’s most popular Lean Kanban conference of this world wide series. Two days packed with inspiring talks, and networking opportunities."}
 - {title: "Social Event", image: "socialevent.jpg", text: "Enjoy an evening of exchanging ideas, meeting new people and your favorite speaker while having a drink." }
 - {title: "Hotel", image: "scandic.jpg", text: 'The Scandic Hamburg Emporio Hotel, right next to venue offers attendees of the conference a 15% discount. Just <a href="https://www.scandichotels.com/hotelreservation/select-rate?hotel=550&fromDate=2019-11-06&toDate=2019-11-08&room%5b0%5d.adults=1&bookingCode=&_ga=2.147564663.1321593296.1562772338-1113290766.1562320056">click here</a> and use the code PART.'}

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of Lean and Kanban"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from all over the world"}
 - {count: "2", specialCharacter: "", info: "parallel tracks", detail: "with 26 talks"}

# Latest News Block
latestNewsTitle: "Latest news"

# Keynote Speakers Block
keynoteSpeakersImage: "background.jpg"
keynoteSpeakersCount: 3
keynoteSpeakersTitle: "Keynote Speakers LKCE2019"
keynoteSpeakersButtonText: "Learn more about the keynote speakers and other speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Panoramadeck"
eventLocationLink: "https://www.nordevent.de/de/eventlocation-details/das-nord-event-panoramadeck.html"
eventStreetAddress: "Dammtorwall 15"
eventAddressLocality: "Hamburg"
eventAddressLocalityRegion: "Hamburg"
eventPostalCode: "20355"
eventAddressCountry: "Germany"
eventStartTime: "2019-11-05T10:00"
eventDoorTime: "09:00"
eventEndTime: "2019-11-06T18:00"
eventPlaceCoordinates: "53.5561441, 9.9822282"
mapCenterCoordinates: "53.5561441,9.9822282"
mapMobileCenterCoordinates: "53.5561441,9.9822282"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "NORD EVENT Panoramadeck"
venueFeatures: ["2 rooms", "Market place to connect and discuss", "Lounge to relax and talk", "Located close to the Außenalster"]

# Tweets Feed Block
tweetsFeedImage: "direction-details.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "LKCE19"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners 2019"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://leankanbance.us14.list-manage.com/subscribe?u=2bd0e07c5708b08b6078676f5&id=e3eb8d6386"
subscribeInfo: "We'll keep you updated on a monthly basis"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "LKCE19 - 2 days Ticket"
  price: "1200"
  priceCurrency: "EUR (excl. 19% VAT)"
  ticketsNumber: "1"
  ribbon: ""
  buyButtonLink: "http://ti.to/lkce/lkce19"
  buyButtonText: "Buy Now - the price will go up"
  ticketContentList: ["2 Days", "2 Tracks", "Social Event"]
  validFrom: "2018-11-25T10:00"
  validThrough: "2019-11-04T23:59"

# Footer
socialLinks:
 - {link: "http://twitter.com/LeanKanbanCE", icon: "twitter"}
 - {link: "http://facebook.com/LeanKanbanCE", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://it-agile.de", text: "it-agile GmbH"}
   - {link: "http://leankanban.com", text: "Lean Kanban Inc."}
   - {permalink: "/cod/", text: "Code of Conduct"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:lkce@it-agile.de", text: "lkce@it-agile.de"}
 -
  title: "Legal"
  links:
   - {permalink: "/impressum/", text: "Impressum"}
   - {permalink: "/termsoftrade/", text: "Terms of Trade"}
   - {permalink: "/datenschutz/", text: "Datenschutz"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "lkce"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "It all started 2011 in Munich and since then Lean Kanban Central Europe grew to the biggest and most popular conference on Lean and Kanban. Our mission has always been and will be again in 2018 to host an unforgetable event for system thinkers, managers, leaders, out-of-the-box-thinkers, entrepreneurs, product developers, and people who care about the way they work."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "53.5561441, 9.9822282"
logisticsMapMobileCenterCoordinates: "53.5561441, 9.9822282"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Hamburg"
directionDetailsCards:
 - {title: "Hotel", information: 'The Scandic Hotel, right next to venue offers attendees of the conference a 15% discount. Just <a href="https://www.scandichotels.com/hotelreservation/select-rate?hotel=550&fromDate=2019-11-06&toDate=2019-11-08&room%5b0%5d.adults=1&bookingCode=&_ga=2.147564663.1321593296.1562772338-1113290766.1562320056">click here</a> and use the code PART.'}
 - {title: "From the Airport", information: 'The airport is easily reachable by car, public transport or taxi. More information is available at <a href="http://www.hamburg-airport.de/en/bus_rail_and_transfer.php">airport website</a>.'}
 - {title: "Public Transit", information: 'Take the subway to either Messehallen or Stephansplatz for public transportation to the central station, the airport or anywhere else in Hamburg.'}

# Archive Direction Details Block
archiveDetailsImage: "direction-details.jpg"
archiveDetailsTitle: "Take a tour through LKCE history"

# Logistics Hotels Block
hotelsTitle: "Hotels"

# socialevent
socialeventTitle: "Social Event"
enablesocialevent: true

# About Social Event Block
socialEventBlockTitle: "A night to remember"
aboutSocialEvent: "As a Social Event we are celebrating this year a "Night in Monte Carlo" at the Historic Customs Hall in Hamburg's world-famous Speicherstadt which is part of the UNESCO World Heritage.
Inspired by this historic building where smuggled goods for fancy parties were confiscated we spared no expenses to transport you into a world of fun, cigars, casino, black jack and magic!
Expect an evening with a delicious three-course menu, drinks, gambling and surprises."

# socialevent Location Block
socialeventLocationBlockTitle: "Location"
socialeventLocationName: "Ehemaliges Hauptzollamt ‒ Zollhalle"
socialeventLocationLink: "http://www.hardrock.com/cafes/hamburg/de/"
socialeventStreetAddress: "Alter Wandrahm 20"
socialeventAddressLocality: "Hamburg"
socialeventAddressLocalityRegion: "Hamburg"
socialeventPostalCode: "20457"
socialeventAddressCountry: "Germany"
socialeventTimeTitle: "Meet new friends"
socialeventStartTime: "2019-11-06T18:30"
socialeventDoorTime: "18:30"
socialeventEndTime: "2019-11-06T23:00"
viewOnMap: "View on Google Maps"
socialeventPlaceCoordinates: "53.54647, 10.0006929"
socialeventMapCenterCoordinates: "53.54647, 10.0006929"
socialeventMapMobileCenterCoordinates: "53.54647, 10.0006929"
socialeventPlaceCoordinates: "53.54647, 10.0006929"
socialeventMapCenterCoordinates: "53.54647, 10.0006929"
socialeventMapMobileCenterCoordinates: "53.54647, 10.0006929"
