# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Lean Kanban Central Europe"

email: "lkce@it-agile.de"
description: "World's biggest conference on Lean Kanban!"
baseurl: ""
url: "http://www.leankanbance.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "it-agile GmbH"
organizerAlternateName: "it-agile"
organizerDescription: "Consultancy for Agile methods"
organizerEmail: "lkce@it-agile.de"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.it-agile.de"

# Head
metaKeywords: "event, kanban, lean, modern management, change, it-agile, LKU, agile, hamburg"
twitterAccount: "@LeanKanbanCE"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/cfp-lkce18"
c4sponsorsUrl: "/assets/Sponsoring_LKCE18.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/socialevent/", text: "Social Event"}
 - {permalink: "/cod/", text: "Code of Conduct"}
 - {permalink: "/archive/", text: "Previous Events"}
bottomNavigationLinks:
  - {permalink: "/#tickets", text: "Buy tickets"}
  - {permalink: "/#subscribe", text: "Subscribe for updates"}
rightNavigationButtons:
  - {permalink: "/#tickets", text: "Buy tickets"}

# Hero Block
heroImage: "lkce18.jpg"
heroTitle: "Lean Kanban Central Europe <typeout>"
eventDate: "5th + 6th November, 2018"
typeoutTextValues: '"", "2018"'
typeoutFallback: "2018"
heroButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}
 - {permalink: "/#subscribe", text: "Subscribe for updates"}
 - {permalink: "/assets/Sponsoring_LKCE18.pdf" , text: "Become a sponsor"}

# About Block
aboutTitle: "About Lean Kanban Central Europe"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "Come and join us at the world’s most popular Lean Kanban conference of this world wide series. Two days packed with inspiring talks, workshops and networking opportunities."}
 - {title: "Social Event", image: "hardrock_logo.jpg", text: "Join us at Hard Rock Café Hamburg for an evening of exchanging ideas, meeting new people and your favorite speaker while having a beer with a breath-taking view over the harbour." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of Lean and Kanban"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from all over the world"}
 - {count: "2", specialCharacter: "", info: "parallel tracks", detail: "plus workshops"}

# Latest News Block
latestNewsTitle: "Latest news"

# Keynote Speakers Block
keynoteSpeakersImage: "lkce18.jpg"
keynoteSpeakersCount: 3
keynoteSpeakersTitle: "Keynote Speakers LKCE2018"
keynoteSpeakersButtonText: "Learn more about the keynote speakers and other speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Curio-Haus"
eventLocationLink: "http://www.koflerkompanie.com/locations/hamburg/curiohaus/"
eventStreetAddress: "Rothenbaumchaussee 13"
eventAddressLocality: "Hamburg"
eventAddressLocalityRegion: "Hamburg"
eventPostalCode: "20148"
eventAddressCountry: "Germany"
eventStartTime: "2018-05-07T10:00"
eventDoorTime: "09:00"
eventEndTime: "2018-06-08T18:00"
eventPlaceCoordinates: "53.565018, 9.989006"
mapCenterCoordinates: "53.565018, 9.989006"
mapMobileCenterCoordinates: "53.565018, 9.989006"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Curio-Haus"
venueFeatures: ["3 rooms", "Lounge to relax and talk", "Located close to the Außenalster"]

# Tweets Feed Block
tweetsFeedImage: "direction-details.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "LKCE18"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners 2018"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://leankanbance.us14.list-manage.com/subscribe?u=2bd0e07c5708b08b6078676f5&id=e3eb8d6386"
subscribeInfo: "We'll keep you updated on a monthly basis"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "LKCE18 - 2 days Ticket"
  price: "1000"
  priceCurrency: "EUR (excl. 19% VAT)"
  ticketsNumber: "1"
  ribbon: ""
  buyButtonLink: "http://ti.to/lkce/lkce18"
  buyButtonText: "Buy Now - the price will go up"
  ticketContentList: ["2 Days", "2 Tracks", "Social Event"]
  validFrom: "2018-11-25T10:00"
  validThrough: "2018-09-30T23:59"

# Footer
socialLinks:
 - {link: "http://twitter.com/LeanKanbanCE", icon: "twitter"}
 - {link: "http://facebook.com/LeanKanbanCE", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://it-agile.de", text: "it-agile GmbH"}
   - {link: "http://leankanban.com", text: "Lean Kanban Inc."}
   - {permalink: "/cod/", text: "Code of Conduct"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:lkce@it-agile.de", text: "lkce@it-agile.de"}
 -
  title: "Legal"
  links:
   - {permalink: "/impressum/", text: "Impressum"}
   - {permalink: "/termsoftrade/", text: "Terms of Trade"}
   - {permalink: "/datenschutz/", text: "Datenschutz"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "lkce"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "It all started 2011 in Munich and since then Lean Kanban Central Europe grew to the biggest and most popular conference on Lean and Kanban. Our mission has always been and will be again in 2018 to host an unforgetable event for system thinkers, managers, leaders, out-of-the-box-thinkers, entrepreneurs, product developers, and people who care about the way they work."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "53.565018, 9.989006"
logisticsMapMobileCenterCoordinates: "53.565018, 9.989006"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Hamburg"
directionDetailsCards:
 - {title: "From the Airport", information: 'The airport is easily reachable by car, public transport or taxi. More information is available at <a href="http://www.hamburg-airport.de/en/bus_rail_and_transfer.php">airport website</a>.'}
 - {title: "Public Transit", information: 'Go to Hamburg Dammtor for public transportation to the central station, the airport or anywhere else in Hamburg.'}

# Archive Direction Details Block
archiveDetailsImage: "direction-details.jpg"
archiveDetailsTitle: "Take a tour through LKCE history"

# Logistics Hotels Block
hotelsTitle: "Hotels"

# socialevent
socialeventTitle: "Social Event"
enablesocialevent: true

# About Social Event Block
socialEventBlockTitle: "LKCE18 goes HardRock Café"
aboutSocialEvent: "We are thrilled to announce that this year’s social event will take place at the legendary Hard Rock Café Hamburg!

All attendees at LKCE are invited to a memorable night at the world’s most famous bar.

On Nov. 5th the restaurant will be closed for the public so that all attendees can enjoy an exclusive experience at the Hard Rock Café!

Join us for drinks at a world-class bar, music and great food in a unique atmosphere. Music memorabilia from the extensive music collection adorn the walls, including items from the world's most recognizable musicians.

The Hard Rock Cafe is located on the banks of the Elbe in one of the city's most historic buildings, the Landungsbrücken, with a breath-taking view over the harbor.

A shuttle service will take you from the venue to the Hard Rock Café.

We can’t wait to welcome you in Hamburg and celebrate LKCE’s 8th anniversary in this legendary location. Rock on!"

# socialevent Location Block
socialeventLocationBlockTitle: "Location"
socialeventLocationName: "HardRock Cafe Hamburg"
socialeventLocationLink: "http://www.hardrock.com/cafes/hamburg/de/"
socialeventStreetAddress: "Bei den St. Pauli Landungsbrücken, Brücke 5"
socialeventAddressLocality: "Hamburg"
socialeventAddressLocalityRegion: "Hamburg"
socialeventPostalCode: "20359"
socialeventAddressCountry: "Germany"
socialeventTimeTitle: "Meet new friends"
socialeventStartTime: "2018-11-05T19:00"
socialeventDoorTime: "19:00"
socialeventEndTime: "2018-11-05T23:00"
viewOnMap: "View on Google Maps"
socialeventPlaceCoordinates: "53.5457182, 9.9680636"
socialeventMapCenterCoordinates: "53.5457182, 9.9680636"
socialeventMapMobileCenterCoordinates: "53.5457182, 9.9680636"
socialeventPlaceCoordinates: "53.5457182, 9.9680636"
socialeventMapCenterCoordinates: "53.5457182, 9.9680636"
socialeventMapMobileCenterCoordinates: "53.5457182, 9.9680636"
